apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-stack-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-stack-bot
  template:
    metadata:
      labels:
        app: genai-stack-bot
    spec:
      containers:
        - name: genai-stack-bot
          image: chunyeow/genai-stack-bot:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          env:
            - name: LLM
              value: "llama2"
            - name: NEO4J_URI
              value: "neo4j://neo4j-release.default.svc.cluster.local:7687"
            - name: NEO4J_PASSWORD
              value: "password"
            - name: NEO4J_USERNAME
              value: "neo4j"
            - name: OPENAI_API_KEY
              value: ""
            - name: OLLAMA_BASE_URL
              value: "http://ollama-linux:11434"
            - name: EMBEDDING_MODEL
              value: "sentence_transformer"
            - name: LANGCHAIN_ENDPOINT
              value: ""
            - name: LANGCHAIN_TRACING_V2
              value: ""
            - name: LANGCHAIN_PROJECT
              value: "k8s-langchain"
            - name: LANGCHAIN_API_KEY
              value: ""
            - name: AWS_ACCESS_KEY_ID
              value: ""
            - name: AWS_SECRET_ACCESS_KEY
              value: ""
            - name: AWS_DEFAULT_REGION
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: genai-bot-service
spec:
  ports:
  - name: http-passthrough
    port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app: genai-stack-bot
  type: ClusterIP
