apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-stack-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-stack-api
  template:
    metadata:
      labels:
        app: genai-stack-api
    spec:
      containers:
        - name: genai-stack-api
          image: chunyeow/genai-stack-api:latest
          ports:
            - containerPort: 8504
          env:
            - name: LLM
              value: "llama2"
            - name: NEO4J_URI
              value: "neo4j://neo4j-release.default.svc.cluster.local:7687"
            - name: NEO4J_PASSWORD
              value: "password"
            - name: NEO4J_USERNAME
              value: "neo4j"
            - name: OPENAI_API_KEY
              value: ""
            - name: OLLAMA_BASE_URL
              value: "http://ollama-linux:11434"
            - name: EMBEDDING_MODEL
              value: "sentence_transformer"
            - name: LANGCHAIN_ENDPOINT
              value: ""
            - name: LANGCHAIN_TRACING_V2
              value: ""
            - name: LANGCHAIN_PROJECT
              value: "k8s-langchain"
            - name: LANGCHAIN_API_KEY
              value: ""
            - name: AWS_ACCESS_KEY_ID
              value: ""
            - name: AWS_SECRET_ACCESS_KEY
              value: ""
            - name: AWS_DEFAULT_REGION
              value: ""
          livenessProbe:
            httpGet:
              path: /
              port: 8504
            initialDelaySeconds: 30
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: genai-api-service
spec:
  ports:
  - name: http-passthrough
    port: 8504
    protocol: TCP
    targetPort: 8504
  selector:
    app: genai-stack-api
  type: ClusterIP
