neo4j:
  name: neo4j-standalone
  resources:
    cpu: "0.5"
    memory: "2Gi"

  # Uncomment to set the initial password
  password: "password"

  # Uncomment to use enterprise edition
  #edition: "enterprise"
  #acceptLicenseAgreement: "yes"

volumes:
  data:
    mode: defaultStorageClass
    defaultStorageClass:
      requests:
        storage: 2Gi

env:
  NEO4J_PLUGINS: '["apoc"]'

config:
  dbms.security.procedures.unrestricted: "apoc.*"
